### ISSUE TITLE
filename becomes chat title

### ISSUE THREAD

**Issue by jchubber** [ryanschiang/chatgpt-export#3]
Hi Ryan. Great script. Thank you! I have a feature suggestion: Instead of `chatgpt.json`, the _default_ filename of the export could be `{{chat title}}.json`. If that's problematic, another option could be to make the default filename equal to the chat's UUID.
https://github.com/ryanschiang/chatgpt-export/blob/f0b33c4dd61f00181e64288c793604226e735fb2/src/util/consoleSave.js#L3

Rationale: It would make exporting large numbers of chats easier. (less typing for the person exporting)

Once again: great script and thank you!

**Comment by jchubber** [comment]
For example instead of 

https://github.com/ryanschiang/chatgpt-export/blob/main/src/util/consoleSave.js#L3

you might have

```
          let filename = document.title.replace(/[^\w\s]/gi, '').toLowerCase();
```

**Comment by ryanschiang** [comment]
Hey Jared, great suggestion! Thanks for the feedback!

I've just updated the scripts so now the default filename when exporting is the slugified chat title.

e.g. "Conversation Title" --> "conversation-title.json"

Should be working now for all export formats, but let me know if you run into any problems.
