### ISSUE TITLE
License of this repo

### ISSUE THREAD

**Issue by jsh9** [ryanschiang/chatgpt-export#4]
Hi! I find this tool really useful, and I may want to contribute to it, or use part of its code for my own project. But I didn't see a LICENSE file in this repo.

The lack of a license usually means "all rights reserved and other people can't do anything about the code" (https://opensource.stackexchange.com/a/1721).

Could you confirm that this is indeed your intention?  If not, could you add a LICENSE file to this repo?

Thank you very much!

**Comment by ryanschiang** [comment]
Hello! 

Thanks for opening this issue and your interest in the script.

I've just added an MIT license to the repo, so please see LICENSE for details.

Thanks!

**Comment by jsh9** [comment]
Thank you!
